# Generated by Django 4.0.3 on 2022-06-16 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporttime', models.CharField(max_length=50)),
                ('informer', models.CharField(max_length=500)),
                ('casedescription', models.CharField(max_length=500)),
                ('place', models.CharField(max_length=100)),
                ('criminal', models.CharField(max_length=500)),
                ('explanation', models.CharField(max_length=500)),
                ('despatchtime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50, null=True)),
                ('dob', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=50)),
                ('p_location', models.CharField(max_length=50)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crime.policestation')),
            ],
        ),
        migrations.CreateModel(
            name='Officer_Reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('designation', models.ImageField(upload_to='images/')),
                ('range', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crime.userreg')),
            ],
        ),
        migrations.CreateModel(
            name='Criminals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
                ('contact', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crime.policereg')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timee', models.CharField(max_length=50)),
                ('c_date', models.CharField(max_length=50)),
                ('complaint', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=50)),
                ('status1', models.CharField(max_length=50, null=True)),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crime.policereg')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Crime.userreg')),
            ],
        ),
        migrations.CreateModel(
            name='Blockchain_ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporttime', models.CharField(max_length=50)),
                ('informer', models.CharField(max_length=500)),
                ('casedescription', models.CharField(max_length=500)),
                ('place', models.CharField(max_length=100)),
                ('criminal', models.CharField(max_length=500)),
                ('explanation', models.CharField(max_length=500)),
                ('status', models.IntegerField(null=True)),
                ('status1', models.CharField(max_length=50, null=True)),
                ('count', models.IntegerField(null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crime.complaint')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blockchain_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('designation', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('key', models.CharField(max_length=200, null=True)),
                ('officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crime.officer_reg')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
