# Generated by Django 4.0.3 on 2022-06-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='despatchtime',
            field=models.DateField(auto_now=True),
        ),
    ]
