# Generated by Django 4.0.3 on 2022-06-19 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crime', '0002_alter_fir_despatchtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100, null=True)),
                ('filename', models.CharField(max_length=100, null=True)),
                ('filenumber', models.CharField(max_length=100, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('location1', models.CharField(max_length=100, null=True)),
                ('time1', models.CharField(max_length=100, null=True)),
                ('date1', models.CharField(max_length=100, null=True)),
                ('evidence1', models.CharField(max_length=500, null=True)),
                ('location2', models.CharField(max_length=100, null=True)),
                ('time2', models.CharField(max_length=100, null=True)),
                ('date2', models.CharField(max_length=100, null=True)),
                ('evidence2', models.CharField(max_length=500, null=True)),
                ('location3', models.CharField(max_length=100, null=True)),
                ('time3', models.CharField(max_length=100, null=True)),
                ('date3', models.CharField(max_length=100, null=True)),
                ('evidence3', models.CharField(max_length=500, null=True)),
                ('location4', models.CharField(max_length=100, null=True)),
                ('time4', models.CharField(max_length=100, null=True)),
                ('date4', models.CharField(max_length=100, null=True)),
                ('evidence4', models.CharField(max_length=500, null=True)),
                ('location5', models.CharField(max_length=100, null=True)),
                ('time5', models.CharField(max_length=100, null=True)),
                ('date5', models.CharField(max_length=100, null=True)),
                ('evidence5', models.CharField(max_length=500, null=True)),
                ('location6', models.CharField(max_length=100, null=True)),
                ('time6', models.CharField(max_length=100, null=True)),
                ('date6', models.CharField(max_length=100, null=True)),
                ('evidence6', models.CharField(max_length=500, null=True)),
                ('ledger_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crime.blockchain_ledger')),
            ],
        ),
    ]
