# Generated by Django 4.0.3 on 2022-06-23 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crime', '0006_blockchain_admin_key2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchain_ledger',
            name='casedescription',
        ),
        migrations.RemoveField(
            model_name='blockchain_ledger',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='blockchain_ledger',
            name='criminal',
        ),
        migrations.RemoveField(
            model_name='blockchain_ledger',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='blockchain_ledger',
            name='informer',
        ),
        migrations.RemoveField(
            model_name='blockchain_ledger',
            name='place',
        ),
        migrations.RemoveField(
            model_name='blockchain_ledger',
            name='reporttime',
        ),
        migrations.RemoveField(
            model_name='blockchain_ledger',
            name='status1',
        ),
        migrations.RemoveField(
            model_name='fir',
            name='despatchtime',
        ),
        migrations.AddField(
            model_name='blockchain_ledger',
            name='Remark',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blockchain_ledger',
            name='blockchain_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blockchain_ledger',
            name='blockchain_entry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blockchain_ledger',
            name='fir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crime.fir'),
        ),
        migrations.AddField(
            model_name='blockchain_ledger',
            name='last_status',
            field=models.CharField(default='not active', max_length=100),
        ),
        migrations.AddField(
            model_name='blockchain_ledger',
            name='remarks',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fir',
            name='blockchain_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fir',
            name='blockchain_entry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fir',
            name='blockchain_status',
            field=models.CharField(default='not active', max_length=100),
        ),
        migrations.AddField(
            model_name='fir',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fir',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blockchain_ledger',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
