# Generated by Django 4.0.3 on 2022-06-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crime', '0007_remove_blockchain_ledger_casedescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fir',
            name='complaint_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crime.complaint'),
        ),
    ]
