# Generated by Django 4.0.3 on 2022-06-23 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Crime', '0008_fir_complaint_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain_ledger_encripted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('Remark', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('blockchain_count', models.IntegerField(default=0)),
                ('blockchain_entry_count', models.IntegerField(default=0)),
                ('last_status', models.CharField(default='not active', max_length=100)),
                ('remarks', models.CharField(max_length=200, null=True)),
                ('count', models.IntegerField(null=True)),
                ('fir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crime.fir')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
