# Generated by Django 4.0.3 on 2022-06-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crime', '0009_blockchain_ledger_encripted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockchain_ledger_encripted',
            name='blockchain_count',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='blockchain_ledger_encripted',
            name='blockchain_entry_count',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
