# Generated by Django 4.0.5 on 2022-10-19 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crime', '0012_remove_blockchain_ledger_fir_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer_reg',
            name='range',
        ),
        migrations.AddField(
            model_name='officer_reg',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crime.policereg'),
        ),
    ]
