# Generated by Django 4.0.5 on 2022-10-19 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Crime', '0013_remove_officer_reg_range_officer_reg_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='media/')),
                ('video', models.ImageField(null=True, upload_to='', verbose_name='media/')),
                ('desc', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
