# Generated by Django 4.0.5 on 2022-10-19 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crime', '0014_add_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_evidence',
            name='complaint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crime.complaint'),
        ),
        migrations.AlterField(
            model_name='add_evidence',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crime.userreg'),
        ),
    ]
