# Generated by Django 4.0.5 on 2022-10-19 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crime', '0015_add_evidence_complaint_alter_add_evidence_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_evidence',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crime.policereg'),
        ),
    ]
