# Generated by Django 4.0.5 on 2022-10-19 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Crime', '0016_add_evidence_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='missing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='media/')),
                ('date', models.CharField(max_length=100, null=True)),
                ('desc', models.CharField(max_length=100, null=True)),
                ('complaint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crime.complaint')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crime.policereg')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Crime.userreg')),
            ],
        ),
    ]
