# Generated by Django 4.0.5 on 2022-10-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Crime', '0018_remove_missing_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing',
            name='station_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
